on: [push, pull_request]
name: Check
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Lint
      run: make lint

  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: make test-cover-html
    - name: Store Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: |
          ./out/coverage
          ./out/coverage.html
    - uses: codecov/codecov-action@v1
      with:
        file: ./out/coverage
        fail_ci_if_error: true
        verbose: true
