on: [push, pull_request]
name: Check
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Lint
      run: make lint
    - name: Unit Tests
      run: make test-cover-html
    - name: Store Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: |
          ./out/coverage
          ./out/coverage.html

